uber/h3-js

- .travis.yml
- README.md
- package.json
Putting this PR up to see whether Travis and Coveralls Just Work or whether there's more setup required here. Won't merge until they both report results.
> Travis CI and coveralls setup

- CHANGELOG.md
- package.json
Per the [release process](https://github.com/uber/h3-js/blob/master/RELEASE.md)
> Preparing for release 3.1.0

- CHANGELOG.md
- package.json
Bump version, add release date to CHANGELOG.
> Preparing for release 3.1.1

- CHANGELOG.md
- package.json
> Preparing for release 3.4.1

- .build-emscripten.sh
- out/libh3.js
> Change const to var in generated libh3.js file

- CHANGELOG.md
- package.json
- Updated version
- Updated CHANGELOG
> Preparing for release 3.4.2

- test/h3core.spec.js
Thanks to @isaacbrodsky for catching!
> Fix h3Line test

- CHANGELOG.md
- package.json
- Updated `package.version`
- Updated CHANGELOG
> Preparing for release 3.4.3

- README.md
- doc-files/README.tmpl.md
Updates the URL to `travis-ci.com` in the template and generated README.
> Update Travis CI badge

- CHANGELOG.md
- package.json
> Preparing for release 3.5.0

- CHANGELOG.md
- package.json
- Updates `package.json` version
> Preparing for release 3.6.1

- CHANGELOG.md
- package.json
> Prepare for release 3.6.2

- CHANGELOG.md
- package.json
- Updates package version (and description while I was at it)
> Prepare for release 3.6.4

- .travis.yml
Update the Travis config to include the FOSSA check.
> Add FOSSA check from #47

- CHANGELOG.md
- benchmark/benchmarks.js
- package.json
- Updates version
- Updates CHANGELOG, adding note for #91 
- Adds a couple of benchmarks for integer input
> Prepare for release 3.7.0

- CHANGELOG.md
- package.json
> Preparing for release 3.7.2

- CHANGELOG.md
- package.json
> Prepare for release v4.0.0-rc2

- CHANGELOG.md
- package.json
> Prepare for release v4.0.0-rc4

- CHANGELOG.md
- package.json
> Prepare for release v4.1.0

- CHANGELOG.md
- package.json
> Prepare for release v4.2.1

- CHANGELOG.md
- package.json
- Updates `package.json` version
> Prepare for release v4.3.0
